[info]
name = "" # Name of the bug
discription = "" # Little discription of the bug
discovery_date = 1900-00-00T00:00:00-08:00 # When was it discovered
type = "" # What kind of bug, e.g ICE, invalid code generation etc
effected_versions = [""] # the versions it effects

[resolved]
stable = false
beta = false
nightly = false

[issue]
link = "" # link to the issue

[optional]
last_checked = 1900-00-00T00:00:00-08:00 # When was this bug last tested

[additional]